# Generated by Django 4.1.7 on 2023-04-27 08:29

from django.db import migrations
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='year_month_field',
            field=month.models.MonthField(blank=True, null=True),
        ),
    ]
