# Generated by Django 4.1.7 on 2023-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_remove_slots_year_month_field_slots_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='slot_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
