# Generated by Django 4.1.7 on 2023-04-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_slots_slot_time_alter_slots_slot_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='slot_time',
            new_name='slot_end_time',
        ),
        migrations.AddField(
            model_name='slots',
            name='slot_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
