# Generated by Django 4.1.7 on 2023-05-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_rename_slot_time_slots_slot_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.patient')),
            ],
        ),
    ]
