# Generated by Django 4.1.7 on 2023-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_alter_diagnosis_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='signature',
            field=models.ImageField(upload_to='signatures/'),
        ),
    ]
